export const cursosInfo = [
  {
    certificado: false,
    countdown: "2024-07-20T14:00:00",
    descripcion:
      "Charla taller destinado a: Bomberos, policías, enfermeros/as y todos aquellos que sufran por su pasión",
    fecha: "20 de Julio 2024",
    horario: "14:00",
    id: "j29323nf9238832",
    localidad: "Carmen De Patagones",
    lugar: "B° Bañado M. Mora 181",
    titulo: "Primeros Socorros Psicológicos",
  },
  {
    certificado: true,
    countdown: "2024-07-11T20:00:00",
    descripcion:
      "Este curso permitirá al profesional adquirir conocimientos y desarrollar competencias sobre el soporte vital básico y avanzado y el reconocimiento de cuadros como taquiarritmias, bradiarritmias y shock, entre otros, para su correcto abordaje y tratamiento.",
    fecha: "11 de Julio 2024",
    horario: "20:00",
    id: "6292d11043b3f79e32ce4a622",
    localidad: "Trenque Lauquen",
    lugar: "VIANI 230",
    titulo: "Socorrismo urbano con RCP y DEA",
  },
  {
    certificado: false,
    countdown: "2024-07-05T20:00:00",
    descripcion:
      "¡Aprendé a salvar vidas con este taller! Cómo proceder ante fracturas, inmovilización, traslados y cuidados en caso de accidentes.",
    fecha: "5 de Julio 2024",
    horario: "20:00",
    id: "6292d11043b3f73455",
    localidad: "Trenque Lauquen",
    lugar: "9 de Julio 267",
    titulo: "Charla-taller para MOTOCICLISTAS. Primeros auxilios con RCP y DEA",
    link: "https://forms.gle/QKbZL7P9m5gfowGD6",
  },
  {
    certificado: false,
    countdown: "2022-05-17T14:20:00",
    descripcion:
      "Este curso permitirá al profesional adquirir conocimientos y desarrollar competencias sobre el soporte vital básico y avanzado y el reconocimiento de cuadros como taquiarritmias, bradiarritmias y shock, entre otros, para su correcto abordaje y tratamiento.",
    fecha: "15 de Abril 2023",
    horario: "20:30",
    id: "6292d11043b3f79e32ce4a62",
    localidad: "Pellegrini",
    lugar: "No definido",
    titulo: "Socorrismo urbano con RCP y DEA",
  },
  {
    certificado: true,
    countdown: "2022-12-16T14:20:00",
    descripcion:
      "Este curso permitirá al profesional adquirir conocimientos y desarrollar competencias sobre el soporte vital básico y avanzado y el reconocimiento de cuadros como taquiarritmias, bradiarritmias y shock, entre otros, para su correcto abordaje y tratamiento.",
    fecha: "16 de Diciembre 2023",
    horario: "20:00",
    id: "639249ae3c4f49d7072094ec",
    localidad: "Trenque Lauquen",
    lugar: "Viani 230",
    titulo: "Socorrismo urbano con RCP y DEA",
  },
  {
    certificado: false,
    countdown: "2022-05-17T14:20:00",
    descripcion:
      "Socorrismo Urbano con RCP y uso del DEA a personal de la empresa IBERCOM-MULTICOM Fibra Optica de la Seccional Trenque Lauquen",
    fecha: "10 de Febrero 2023",
    horario: "19:00",
    id: "63ee523b3dac54a8e3426408",
    localidad: "Trenque Lauquen",
    lugar: "Empresa IBERCOM-MULTICOM",
    titulo: "Socorrismo urbano con RCP y DEA",
  },
  {
    certificado: true,
    countdown: "2023-02-15T09:30:00",
    descripcion: "Cupos completos",
    fecha: "22 de Abril 2023",
    horario: "17:00",
    id: "641580fde7e333173c049345",
    localidad: "Trenque Lauquen",
    lugar: "Ludoteca Dulces Horas - Mitre y Belgrano",
    titulo: "Socorrismo urbano con RCP y DEA",
  },
  {
    certificado: true,
    countdown: "2023-04-15T09:30:00",
    descripcion:
      "Este curso permitirá al profesional adquirir conocimientos y desarrollar competencias sobre el soporte vital básico y avanzado y el reconocimiento de cuadros como taquiarritmias, bradiarritmias y shock, entre otros, para su correcto abordaje y tratamiento.",
    fecha: "15 de Abril 2023",
    horario: "9:30",
    id: "6419ad8b627a78bf6759817b",
    localidad: "Tres Lomas",
    lugar: "Kulá Centro de salud integral",
    titulo: "Socorrismo urbano con RCP y DEA",
  },
];
