export const cursosInfo = [
  {
    certificado: true,
    countdown: "2025-01-03T20:00:00",
    descripcion: "Curso de socorrismo urbano RCP y DEA",
    fecha: "3 de Enero 2025",
    horario: "20:00",
    id: "13",
    localidad: "Fortín Olavarría",
    lugar: "Fortín Olavarría",
    titulo: "RCP y DEA",
  },
  {
    certificado: true,
    countdown: "2024-12-07T09:00:00",
    descripcion:
      "Curso de socorrismo urbano RCP y DEA más Primeros auxilios Pediátricos",
    fecha: "7 de Diciembre 2024",
    horario: "09:00",
    id: "12",
    localidad: "Trenque Lauquen",
    lugar: "Ludoteca dulces horas",
    titulo: "RCP, DEA y primeros auxilios",
  },
  {
    certificado: true,
    countdown: "2024-10-17T20:00:00",
    descripcion: "Curso de socorrismo urbano RCP y DEA",
    fecha: "17 de Octubre 2024",
    horario: "20:00",
    id: "11",
    localidad: "Trenque Lauquen",
    lugar: "Viani 230",
    titulo: "RCP y uso de DEA",
  },
  {
    certificado: true,
    countdown: "2024-09-10T20:00:00",
    descripcion: "Curso de primeros socorros con RCP y uso del DEA",
    fecha: "10 de Septiembre 2024",
    horario: "20:00",
    id: "10",
    localidad: "Trenque Lauquen",
    lugar: "Viani 230",
    titulo: "RCP y uso de DEA",
  },
  {
    certificado: true,
    countdown: "2024-08-03T09:30:00",
    descripcion: "Taller de primeros auxilios infantiles y adultos",
    fecha: "3 de Agosto 2024",
    horario: "9:30",
    id: "9",
    localidad: "Trenque Lauquen",
    lugar: "Farrington 172",
    titulo: "RCP y uso de DEA",
  },
  {
    certificado: false,
    countdown: "2024-07-20T14:00:00",
    descripcion:
      "Charla taller destinado a: Bomberos, policías, enfermeros/as y todos aquellos que sufran por su pasión",
    fecha: "20 de Julio 2024",
    horario: "14:00",
    id: "8",
    localidad: "Carmen De Patagones",
    lugar: "B° Bañado M. Mora 181",
    titulo: "Primeros Socorros Psicológicos",
  },
  {
    certificado: true,
    countdown: "2024-07-11T20:00:00",
    descripcion:
      "Este curso permitirá al profesional adquirir conocimientos y desarrollar competencias sobre el soporte vital básico y avanzado y el reconocimiento de cuadros como taquiarritmias, bradiarritmias y shock, entre otros, para su correcto abordaje y tratamiento.",
    fecha: "11 de Julio 2024",
    horario: "20:00",
    id: "7",
    localidad: "Trenque Lauquen",
    lugar: "VIANI 230",
    titulo: "Socorrismo urbano con RCP y DEA",
  },
  {
    certificado: false,
    countdown: "2024-07-05T20:00:00",
    descripcion:
      "¡Aprendé a salvar vidas con este taller! Cómo proceder ante fracturas, inmovilización, traslados y cuidados en caso de accidentes.",
    fecha: "5 de Julio 2024",
    horario: "20:00",
    id: "6",
    localidad: "Trenque Lauquen",
    lugar: "9 de Julio 267",
    titulo: "Charla-taller para MOTOCICLISTAS. Primeros auxilios con RCP y DEA",
    link: "https://forms.gle/QKbZL7P9m5gfowGD6",
  },
  {
    certificado: false,
    countdown: "2022-05-17T14:20:00",
    descripcion:
      "Este curso permitirá al profesional adquirir conocimientos y desarrollar competencias sobre el soporte vital básico y avanzado y el reconocimiento de cuadros como taquiarritmias, bradiarritmias y shock, entre otros, para su correcto abordaje y tratamiento.",
    fecha: "15 de Abril 2023",
    horario: "20:30",
    id: "5",
    localidad: "Pellegrini",
    lugar: "No definido",
    titulo: "Socorrismo urbano con RCP y DEA",
  },
  {
    certificado: true,
    countdown: "2022-12-16T14:20:00",
    descripcion:
      "Este curso permitirá al profesional adquirir conocimientos y desarrollar competencias sobre el soporte vital básico y avanzado y el reconocimiento de cuadros como taquiarritmias, bradiarritmias y shock, entre otros, para su correcto abordaje y tratamiento.",
    fecha: "16 de Diciembre 2023",
    horario: "20:00",
    id: "4",
    localidad: "Trenque Lauquen",
    lugar: "Viani 230",
    titulo: "Socorrismo urbano con RCP y DEA",
  },
  {
    certificado: false,
    countdown: "2022-05-17T14:20:00",
    descripcion:
      "Socorrismo Urbano con RCP y uso del DEA a personal de la empresa IBERCOM-MULTICOM Fibra Optica de la Seccional Trenque Lauquen",
    fecha: "10 de Febrero 2023",
    horario: "19:00",
    id: "3",
    localidad: "Trenque Lauquen",
    lugar: "Empresa IBERCOM-MULTICOM",
    titulo: "Socorrismo urbano con RCP y DEA",
  },
  {
    certificado: true,
    countdown: "2023-02-15T09:30:00",
    descripcion: "Cupos completos",
    fecha: "22 de Abril 2023",
    horario: "17:00",
    id: "2",
    localidad: "Trenque Lauquen",
    lugar: "Ludoteca Dulces Horas - Mitre y Belgrano",
    titulo: "Socorrismo urbano con RCP y DEA",
  },
  {
    certificado: true,
    countdown: "2023-04-15T09:30:00",
    descripcion:
      "Este curso permitirá al profesional adquirir conocimientos y desarrollar competencias sobre el soporte vital básico y avanzado y el reconocimiento de cuadros como taquiarritmias, bradiarritmias y shock, entre otros, para su correcto abordaje y tratamiento.",
    fecha: "15 de Abril 2023",
    horario: "9:30",
    id: "1",
    localidad: "Tres Lomas",
    lugar: "Kulá Centro de salud integral",
    titulo: "Socorrismo urbano con RCP y DEA",
  },
];
